## Apress - Industrialized Machine Learning Examples

Andreas Francois Vermeulen
2019

### This is an example add-on to a book and needs to be accepted as part of that copyright.

## Chapter-007-001-Neural-Networks-Autoencoder-01

In [1]:
import numpy as np

In [2]:
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [3]:
# input dataset
X = np.array([
                [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1]
             ])
print(X)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [4]:
# output dataset            
y = np.array([[0,0,1,1]]).T

print(y)

[[0]
 [0]
 [1]
 [1]]


In [5]:
np.random.seed(1968)

# initialize weights randomly with mean 0
SynZero = 2*np.random.random((3,1)) - 1

In [6]:
for iter in range(10000):

    # forward propagation
    LZero = X
    LOne = nonlin(np.dot(LZero,SynZero))

    # how much did we miss?
    LOne_error = y - LOne

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    LOne_delta = LOne_error * nonlin(LOne, True)

    # update weights
    SynZero += np.dot(LZero.T, LOne_delta)

In [7]:
print ('Output After Training:')
print (LOne)

Output After Training:
[[0.00966553]
 [0.00786406]
 [0.99359009]
 [0.99211908]]


In [8]:
print ('Output After Stepper function:')
print(LOne.round(0))

Output After Stepper function:
[[0.]
 [0.]
 [1.]
 [1.]]


## Done

In [9]:
import datetime
now = datetime.datetime.now()
print('Done!',str(now))

Done! 2019-10-19 20:01:05.209035
