## Apress - Industrialized Machine Learning Examples

Andreas Francois Vermeulen
2019

### This is an example add-on to a book and needs to be accepted as part of that copyright.

# Chapter-009-001-Markov-Decision-Process-01

In [1]:
import numpy as np

In [2]:
#Declaring the Transition Matrix T
T = np.array([[0.90, 0.10],
              [0.50, 0.50]])

In [3]:
#Obtaining T after 3 steps
T_3 = np.linalg.matrix_power(T, 3)
#Obtaining T after 50 steps
T_50 = np.linalg.matrix_power(T, 50)
#Obtaining T after 100 steps
T_100 = np.linalg.matrix_power(T, 100)


In [6]:
#Printing the matrices
print("T: \n" + str(T))
print("T_3: \n" + str(T_3))
print("T_50: \n" + str(T_50))
print("T_100: \n" + str(T_100))

T: 
[[0.9 0.1]
 [0.5 0.5]]
T_3: 
[[0.844 0.156]
 [0.78  0.22 ]]
T_50: 
[[0.83333333 0.16666667]
 [0.83333333 0.16666667]]
T_100: 
[[0.83333333 0.16666667]
 [0.83333333 0.16666667]]


## Done

In [5]:
import datetime
now = datetime.datetime.now()
print('Done!',str(now))

Done! 2019-04-24 18:45:57.013068
