## Apress - Industrialized Machine Learning Examples

Andreas Francois Vermeulen
2019

### This is an example add-on to a book and needs to be accepted as part of that copyright.

## Chapter-009-011-MQN-01

In [1]:
import numpy as np
# Generate three random clusters of 2D data
N_c = 8
A = 0.6*np.random.randn(N_c, 2)+[1, 1]
B = 0.6*np.random.randn(N_c, 2)+[3, 3]
C = 0.6*np.random.randn(N_c, 2)+[3, 0]
X = np.hstack((np.ones(3*N_c).reshape(3*N_c, 1), np.vstack((A, B, C))))
Y = np.vstack(((np.zeros(N_c)).reshape(N_c, 1), 
        np.ones(N_c).reshape(N_c, 1), 2*np.ones(N_c).reshape(N_c, 1)))
K = 3
N = K*N_c

# Next we run gradient descent using the multinomial logistic regression gradient: 

# Run gradient descent
eta = 1E-2
max_iter = 8000
w = np.zeros((3, 3))
grad_thresh = 5 
for t in range(0, max_iter):
    grad_t = np.zeros((3, 3))
    for i in range(0, N):
        x_i = X[i, :]
        y_i = Y[i]
        exp_vals = np.exp(w.dot(x_i))
        lik = exp_vals[int(y_i)]/np.sum(exp_vals)
        grad_t[int(y_i), :] += x_i*(1-lik)

    w = w + 1/float(N)*eta*grad_t
    grad_norm = np.linalg.norm(grad_t)

    if grad_norm < grad_thresh:
        print ("Converged in ",t+1,"steps.")
        print('Queue A:')
        print(A)
        print('Queue B:')
        print(B)
        print('Queue C:')
        print(C)
        break

    if t == max_iter-1:
        print ("Warning, did not converge.")
    

Converged in  2910 steps.
Queue A:
[[ 0.42527441  1.45932545]
 [ 0.76109068  0.48853422]
 [-0.17117237  0.17905512]
 [-0.54519942  0.73322936]
 [ 1.36783343  1.10589307]
 [ 0.98149962  0.91399272]
 [ 0.59364362  0.34726429]
 [ 1.02589844  1.36681085]]
Queue B:
[[2.45321381 2.28736704]
 [3.98844546 4.16390991]
 [3.16064366 3.52105067]
 [3.67223323 2.53729862]
 [2.89746061 2.78443157]
 [3.29410877 2.61841516]
 [3.05434808 2.24152433]
 [2.7875369  3.35974475]]
Queue C:
[[ 2.90659169e+00  3.31039656e-01]
 [ 2.48937515e+00  6.71534823e-04]
 [ 3.38060952e+00 -6.82259148e-01]
 [ 2.50420641e+00  5.98281112e-01]
 [ 2.92537373e+00  4.20414310e-01]
 [ 3.50970721e+00 -4.12968299e-01]
 [ 2.76275538e+00  3.75675482e-01]
 [ 2.51677210e+00  6.90864065e-01]]


## Done

In [2]:
import datetime
now = datetime.datetime.now()
print('Done!',str(now))

Done! 2019-04-24 21:24:05.597748
