## Apress - Industrialized Machine Learning Examples

Andreas Francois Vermeulen
2019

### This is an example add-on to a book and needs to be accepted as part of that copyright.

# Chapter 004 Example 008

## Part A - Load libraries

In [1]:
from sklearn.naive_bayes import MultinomialNB
import pandas as pd
import os
import numpy as np
import random as r

## Part B - Load Data

In [2]:
fileName = '../../Data/Roses01.csv'
fileFullName = os.path.abspath(fileName)
print(fileFullName)

C:\Users\AndreVermeulen\Documents\My Book\apress\Industrialized Machine Learning\book\IML\Data\Roses01.csv


In [3]:
rosesdf= pd.read_csv(fileFullName,header=0)
print(rosesdf.shape)
print(rosesdf.columns)

(150, 6)
Index(['F01', 'F02', 'F03', 'F04', 'T', 'T2'], dtype='object')


In [4]:
X_raw = np.array(rosesdf[['F01', 'F02', 'F03', 'F04']]) 
Y = np.array(rosesdf['T'])

## Part C - Load Data Feature F01, F02, F03 and F04 and test for mislabeled data

In [5]:
X = np.array(X_raw[:,[0,1,2,3]]) 
mnb = MultinomialNB()
y_pred = mnb.fit(X, Y).predict(X)
tot=X.shape[0]
totwrong=(Y != y_pred).sum()
perswrong=(totwrong/tot) * 100
print("Number of mislabeled Rose Feature F01, F02, F03 and F04 points out of a total %d points : %d => %7.3f %%" % (tot, totwrong, perswrong))

Number of mislabeled Rose Feature F01, F02, F03 and F04 points out of a total 150 points : 7 =>   4.667 %


In [6]:
print('Smoothed empirical log probability for each class:')
print(mnb.class_log_prior_)

Smoothed empirical log probability for each class:
[-1.09861229 -1.09861229 -1.09861229]


In [7]:
print('Mirrors class_log_prior_ for interpreting MultinomialNB as a linear model:')
print(mnb.intercept_)

Mirrors class_log_prior_ for interpreting MultinomialNB as a linear model:
[-1.09861229 -1.09861229 -1.09861229]


In [8]:
print('Empirical log probability of features given a class, P(x_i|y):')
print(mnb.feature_log_prob_)

Empirical log probability of features given a class, P(x_i|y):
[[-0.70893906 -1.08867359 -1.92882235 -3.65536968]
 [-0.88088275 -1.63924027 -1.21132886 -2.36814464]
 [-0.95779046 -1.74946121 -1.12831744 -2.13018483]]


In [9]:
print('Mirrors feature_log_prob_ for interpreting MultinomialNB as a linear model:')
print(mnb.coef_)

Mirrors feature_log_prob_ for interpreting MultinomialNB as a linear model:
[[-0.70893906 -1.08867359 -1.92882235 -3.65536968]
 [-0.88088275 -1.63924027 -1.21132886 -2.36814464]
 [-0.95779046 -1.74946121 -1.12831744 -2.13018483]]


In [10]:
print('Number of samples encountered for each (class, feature) during fitting:')
print(mnb.feature_count_)

Number of samples encountered for each (class, feature) during fitting:
[[250.3 170.9  73.2  12.2]
 [296.8 138.5 213.   66.3]
 [329.4 148.7 277.6 101.3]]


## Done

In [11]:
import datetime
now = datetime.datetime.now()
print('Done!',str(now))

Done! 2019-04-08 11:05:28.091874
