## Apress - Industrialized Machine Learning Examples

Andreas Francois Vermeulen
2019

### This is an example add-on to a book and needs to be accepted as part of that copyright.

# Chapter 004 Example 007

## Part A - Load libraries

In [1]:
from sklearn.naive_bayes import GaussianNB
import pandas as pd
import os
import numpy as np

## Part B - Load Data

In [2]:
fileName = '../../Data/Roses01.csv'
fileFullName = os.path.abspath(fileName)
print(fileFullName)

C:\Users\AndreVermeulen\Documents\My Book\apress\Industrialized Machine Learning\book\IML\Data\Roses01.csv


In [3]:
rosesdf= pd.read_csv(fileFullName,header=0)
print(rosesdf.shape)
print(rosesdf.columns)

(150, 6)
Index(['F01', 'F02', 'F03', 'F04', 'T', 'T2'], dtype='object')


In [4]:
X_raw = np.array(rosesdf[['F01', 'F02', 'F03', 'F04']]) 
Y = np.array(rosesdf['T'])

## Part C - Load Data Feature F01 and test for mislabeled data

In [5]:
X = np.array(X_raw[:,[0]]) 
gnb1 = GaussianNB()
y_pred = gnb1.fit(X, Y).predict(X)
tot=X.shape[0]
totwrong=(Y != y_pred).sum()
perswrong=(totwrong/tot) * 100
print("Number of mislabeled Rose Feature F01 points out of a total %d points : %d => %7.3f %%" % (tot, totwrong, perswrong))

Number of mislabeled Rose Feature F01 points out of a total 150 points : 41 =>  27.333 %


In [6]:
print('Probability of each class:')
print(gnb1.class_prior_)

Probability of each class:
[0.33333333 0.33333333 0.33333333]


In [7]:
print('Number of training samples observed in each class:')
print(gnb1.class_count_)

Number of training samples observed in each class:
[50. 50. 50.]


In [8]:
print('Mean of each feature per class:')
print(gnb1.theta_)

Mean of each feature per class:
[[5.006]
 [5.936]
 [6.588]]


In [9]:
print('Variance of each feature per class:')
print(gnb1.sigma_)

Variance of each feature per class:
[[0.121764]
 [0.261104]
 [0.396256]]


In [10]:
print('Absolute additive value to variances:')
print(gnb1.epsilon_)

Absolute additive value to variances:
6.811222222222224e-10


## Part D - Load Data Feature F02 and test for mislabeled data

In [11]:
X = np.array(X_raw[:,[1]]) 
gnb2 = GaussianNB()
y_pred = gnb2.fit(X, Y).predict(X)
tot=X.shape[0]
totwrong=(Y != y_pred).sum()
perswrong=(totwrong/tot) * 100
print("Number of mislabeled Rose Feature F02 points out of a total %d points : %d => %7.3f %%" % (tot, totwrong, perswrong))

Number of mislabeled Rose Feature F02 points out of a total 150 points : 68 =>  45.333 %


In [12]:
print('Probability of each class:')
print(gnb2.class_prior_)

Probability of each class:
[0.33333333 0.33333333 0.33333333]


In [13]:
print('Number of training samples observed in each class:')
print(gnb2.class_count_)

Number of training samples observed in each class:
[50. 50. 50.]


In [14]:
print('Mean of each feature per class:')
print(gnb2.theta_)

Mean of each feature per class:
[[3.418]
 [2.77 ]
 [2.974]]


In [15]:
print('Variance of each feature per class:')
print(gnb2.sigma_)

Variance of each feature per class:
[[0.142276]
 [0.0965  ]
 [0.101924]]


In [16]:
print('Absolute additive value to variances:')
print(gnb2.epsilon_)

Absolute additive value to variances:
1.8675066666666667e-10


## Part E - Load Data Feature F03 and test for mislabeled data

In [17]:
X = np.array(X_raw[:,[2]]) 
gnb3 = GaussianNB()
y_pred = gnb3.fit(X, Y).predict(X)
tot=X.shape[0]
totwrong=(Y != y_pred).sum()
perswrong=(totwrong/tot) * 100
print("Number of mislabeled Rose Feature F03 points out of a total %d points : %d => %7.3f %%" % (tot, totwrong, perswrong))

Number of mislabeled Rose Feature F03 points out of a total 150 points : 7 =>   4.667 %


In [18]:
print('Probability of each class:')
print(gnb3.class_prior_)

Probability of each class:
[0.33333333 0.33333333 0.33333333]


In [19]:
print('Number of training samples observed in each class:')
print(gnb3.class_count_)

Number of training samples observed in each class:
[50. 50. 50.]


In [20]:
print('Mean of each feature per class:')
print(gnb3.theta_)

Mean of each feature per class:
[[1.464]
 [4.26 ]
 [5.552]]


In [21]:
print('Variance of each feature per class:')
print(gnb3.sigma_)

Variance of each feature per class:
[[0.029504]
 [0.2164  ]
 [0.298496]]


In [22]:
print('Absolute additive value to variances:')
print(gnb3.epsilon_)

Absolute additive value to variances:
3.092424888888889e-09


## Part F - Load Data Feature F04 and test for mislabeled data

In [23]:
X = np.array(X_raw[:,[3]]) 
gnb4 = GaussianNB()
y_pred = gnb4.fit(X, Y).predict(X)
tot=X.shape[0]
totwrong=(Y != y_pred).sum()
perswrong=(totwrong/tot) * 100
print("Number of mislabeled Rose Feature F04 points out of a total %d points : %d => %7.3f %%" % (tot, totwrong, perswrong))

Number of mislabeled Rose Feature F04 points out of a total 150 points : 6 =>   4.000 %


In [24]:
print('Probability of each class:')
print(gnb4.class_prior_)

Probability of each class:
[0.33333333 0.33333333 0.33333333]


In [25]:
print('Number of training samples observed in each class:')
print(gnb4.class_count_)

Number of training samples observed in each class:
[50. 50. 50.]


In [26]:
print('Mean of each feature per class:')
print(gnb4.theta_)

Mean of each feature per class:
[[0.244]
 [1.326]
 [2.026]]


In [27]:
print('Variance of each feature per class:')
print(gnb4.sigma_)

Variance of each feature per class:
[[0.011264]
 [0.038324]
 [0.073924]]


In [28]:
print('Absolute additive value to variances:')
print(gnb4.epsilon_)

Absolute additive value to variances:
5.785315555555557e-10


## Part G - Load Data Feature F01, F02, F03 and F04 and test for mislabeled data

In [29]:
X = np.array(X_raw[:,[0,1,2,3]]) 
gnb5 = GaussianNB()
y_pred = gnb5.fit(X, Y).predict(X)
tot=X.shape[0]
totwrong=(Y != y_pred).sum()
perswrong=(totwrong/tot) * 100
print("Number of mislabeled Rose Feature F01, F02, F03 and F04 points out of a total %d points : %d => %7.3f %%" % (tot, totwrong, perswrong))

Number of mislabeled Rose Feature F01, F02, F03 and F04 points out of a total 150 points : 6 =>   4.000 %


In [30]:
print('Probability of each class:')
print(gnb5.class_prior_)

Probability of each class:
[0.33333333 0.33333333 0.33333333]


In [31]:
print('Number of training samples observed in each class:')
print(gnb5.class_count_)

Number of training samples observed in each class:
[50. 50. 50.]


In [32]:
print('Mean of each feature per class:')
print(gnb5.theta_)

Mean of each feature per class:
[[5.006 3.418 1.464 0.244]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]


In [33]:
print('Variance of each feature per class:')
print(gnb5.sigma_)

Variance of each feature per class:
[[0.121764 0.142276 0.029504 0.011264]
 [0.261104 0.0965   0.2164   0.038324]
 [0.396256 0.101924 0.298496 0.073924]]


In [34]:
print('Absolute additive value to variances:')
print(gnb5.epsilon_)

Absolute additive value to variances:
3.092424888888889e-09


In [35]:
print(gnb5.get_params(deep=True))

{'priors': None, 'var_smoothing': 1e-09}


## Done

In [36]:
import datetime
now = datetime.datetime.now()
print('Done!',str(now))

Done! 2019-04-08 10:52:11.347850
