## Apress - Industrialized Machine Learning Examples

Andreas Francois Vermeulen
2019

### This is an example add-on to a book and needs to be accepted as part of that copyright.

## Chapter-008-007-Preprocessing-Data-01

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [3]:
X_scaled = preprocessing.scale(X_train)

In [4]:
print(X_scaled)

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [5]:
print(X_scaled.mean(axis=0))

[0. 0. 0.]


In [6]:
print(X_scaled.std(axis=0))

[1. 1. 1.]


In [7]:
print(X_scaled.min(axis=0))

[-1.22474487 -1.22474487 -1.06904497]


In [8]:
print(X_scaled.max(axis=0))

[1.22474487 1.22474487 1.33630621]


In [9]:
scaler = preprocessing.StandardScaler().fit(X_train)

In [10]:
print(scaler)

StandardScaler(copy=True, with_mean=True, with_std=True)


In [11]:
print(scaler.mean_)

[1.         0.         0.33333333]


In [12]:
print(scaler.scale_)

[0.81649658 0.81649658 1.24721913]


In [13]:
print(scaler.transform(X_train))

[[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [14]:
X_test = [[-1., 1., 0.]]

In [15]:
print(scaler.transform(X_test))

[[-2.44948974  1.22474487 -0.26726124]]


## Done

In [ ]:
import datetime
now = datetime.datetime.now()
print('Done!',str(now))