## Apress - Industrialized Machine Learning Examples

Andreas Francois Vermeulen
2019

### This is an example add-on to a book and needs to be accepted as part of that copyright.

# Chapter 05 Example 004

In [1]:
#!pip install --upgrade tensorflow

## Part A - Load Libraries

In [2]:
import tensorflow as tf
import numpy as np

## Part B - Basic constant operations
### The value returned by the constructor represents the output of the Constant operator.

In [3]:
a = np.array(5.0, dtype=np.float64)
b = np.array(10.0, dtype=np.float64)
c = np.array(20.0, dtype=np.float64)
d = np.array(12.0, dtype=np.float64)
e = np.array(89.0, dtype=np.float64)
f = np.array(2.0, dtype=np.float64)

tf_a = tf.constant(a)
tf_b = tf.constant(b)
tf_c = tf.constant(c)
tf_d = tf.constant(d)
tf_e = tf.constant(e)
tf_f = tf.constant(f)

tf_s = tf.sqrt(tf_e)
tf_x = tf.math.add_n([tf_a,tf_b,tf_c])
tf_y = tf.multiply(tf.multiply(tf_a,tf_b),tf_c)
tf_z = tf.pow(tf_f,tf_d)

with tf.Session() as sess:
    print("a=%0.3f, b=%0.3f, c=%0.3f, d=%0.3f, e=%0.3f" % (a,b,c,d,e))
    print("x=%0.3f + %0.3f + %0.3f" % (a,b,c))
    print("Addition with constants: x = %i" % sess.run(tf_x))
    
    print("y=%0.3f x %0.3f x %0.3f" % (a,b,c))
    print("Multiplication with constants: y = %i" % sess.run(tf_y))
    
    print("z=%0.3f ^ %0.3f" % (f,d))    
    print("Power with constants: z = %i" % sess.run(tf_z))
    
    print("s=sqrt(%0.3f)" % (e))    
    print("Square root with constants: s = %i" % sess.run(tf_s))

a=5.000, b=10.000, c=20.000, d=12.000, e=89.000
x=5.000 + 10.000 + 20.000
Addition with constants: x = 35
y=5.000 x 10.000 x 20.000
Multiplication with constants: y = 1000
z=2.000 ^ 12.000
Power with constants: z = 4096
s=sqrt(89.000)
Square root with constants: s = 9


## Part C - Basic Operations with variable as graph input
### The value returned by the constructor represents the output
### of the Variable operator. (Define it as an input when running session)
### tf Graph input

In [4]:
a = tf.placeholder(tf.float64)
b = tf.placeholder(tf.float64)
c = tf.placeholder(tf.float64)

# Define more operations
add = tf.add(tf.add(a, b),c)
mul = tf.multiply(tf.multiply(a, b),c)

# Launch the default graph.
with tf.Session() as sess:
    # Run every operation with variable input
    print("Addition with variables: %i" % sess.run(add, feed_dict={a: 5.0, b: 10.0, c: 20.0}))
    print("Multiplication with variables: %i" % sess.run(mul, feed_dict={a: 5.0, b: 10.0, c: 20.0}))


Addition with variables: 35
Multiplication with variables: 1000


## Part D - Matrix Multiplication from TensorFlow

### Create a Constant op that produces a 1x3 matrix.  The operator is added as a node to the default graph.
### The value returned by the constructor represents the output of the Constant operator.

In [5]:
matrix1 = tf.constant([[10., 11., 12.,13.]])
print(matrix1)
# Create another Constant that produces a 3x1 matrix.
matrix2 = tf.constant([[14.],[15.],[16.],[17.]])
print(matrix2)

Tensor("Const_6:0", shape=(1, 4), dtype=float32)
Tensor("Const_7:0", shape=(4, 1), dtype=float32)


## Part E - Create a Matmul op that takes 'matrix1' and 'matrix2' as inputs.
### The returned value, 'product', represents the result of the matrix multiplication.

In [6]:
product = tf.matmul(matrix1, matrix2)

### To run the matmul op we call the session 'run()' method, passing 'product'
### which represents the output of the matmul op.  This indicates to the call
### that we want to get the output of the matmul op back.
### All inputs needed by the op are run automatically by the session.  They
### typically are run in parallel.
### The call 'run(product)' thus causes the execution of threes ops in the
### graph: the two constants and matmul.
### The output of the op is returned in 'result' as a numpy `ndarray` object.

## Part F - Run the TF session

In [7]:
with tf.Session() as sess:
    result = sess.run(product)
    print(result)

[[718.]]


## Part G - Extra Matrix Calculations

In [19]:
i=100
matrix0 = np.array(np.arange(i, 0.0, -1.0),dtype=np.float32)
n=int(matrix0.shape[0])
matrix1 = matrix0.reshape((n,1))
matrix2 = np.transpose(matrix1)
print(matrix0.shape)
print(matrix1.shape)
print(matrix2.shape)

(100,)
(100, 1)
(1, 100)


In [20]:
tf_matrix1 = tf.constant(matrix1)
print(tf_matrix1)
# Create another Constant that produces a 3x1 matrix.
tf_matrix2 = tf.constant(matrix2)
print(tf_matrix2)

Tensor("Const_12:0", shape=(100, 1), dtype=float32)
Tensor("Const_13:0", shape=(1, 100), dtype=float32)


In [21]:
tf_product = tf.matmul(tf_matrix1, tf_matrix2)

In [22]:
with tf.Session() as sess:
    tf_result = sess.run(tf_product)
    print(tf_result.shape)
    print(tf_result)

(100, 100)
[[1.000e+04 9.900e+03 9.800e+03 ... 3.000e+02 2.000e+02 1.000e+02]
 [9.900e+03 9.801e+03 9.702e+03 ... 2.970e+02 1.980e+02 9.900e+01]
 [9.800e+03 9.702e+03 9.604e+03 ... 2.940e+02 1.960e+02 9.800e+01]
 ...
 [3.000e+02 2.970e+02 2.940e+02 ... 9.000e+00 6.000e+00 3.000e+00]
 [2.000e+02 1.980e+02 1.960e+02 ... 6.000e+00 4.000e+00 2.000e+00]
 [1.000e+02 9.900e+01 9.800e+01 ... 3.000e+00 2.000e+00 1.000e+00]]


## Done

In [18]:
import datetime
now = datetime.datetime.now()
print('Done!',str(now))

Done! 2019-04-14 14:36:02.153761
